sudo: false
language: python
python:
  - "3.7"
  - "3.8"
dist:
  bionic

install:
  - pip install tox-travis coveralls pytest-vcr pytest-mock pytest-asyncio hbmqtt
  - python setup.py develop
script:
  - coverage run --source pyess -m py.test
  - coverage report -m
after_success:
  - coveralls

env:
  USE_NETWORK=false