sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
dist:
  xenial
#matrix:
#  include:
#    - python: 3.7
#      dist: xenial
#      sudo: true
install:
  - pip install tox-travis coveralls pytest-vcr
  - python setup.py develop
script:
  - coverage run --source pyess -m py.test
  - coverage report -m
after_success:
  - coveralls

env:
  USE_NETWORK=false